# Generated by Django 3.1.7 on 2021-06-04 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_auto_20210604_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrangement',
            name='method',
        ),
        migrations.RemoveField(
            model_name='arrangement',
            name='path',
        ),
        migrations.RemoveField(
            model_name='arrangement',
            name='step',
        ),
        migrations.AddField(
            model_name='step',
            name='arrangement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_arrangement', to='gateway.arrangement', verbose_name='编排'),
        ),
    ]
