# Generated by Django 3.1.7 on 2021-06-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_auto_20210604_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='sort',
            field=models.IntegerField(blank=True, default=1, verbose_name='顺序'),
        ),
    ]
